# payments-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: go-kubernetes-payments:latest
          ports:
            - containerPort: 5672
          env:
            - name: GO_ENV
              value: "development"
    # Add volume if you need persitant (database, caching etc.)
    #     volumeMounts:
    #       - name: app-volume
    #         mountPath: /app
    #       - name: go-mod-cache
    #         mountPath: /go/pkg/mod
    # volumes:
    #   - name: app-volume
    #     hostPath:
    #       path: /app
    #   - name: go-mod-cache
    #     hostPath:
    #       path: /go/pkg/mod
---
# payments-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: payments
