# rabbitmq-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
      # Add volume if you need persistent storage (database, caching etc.)
      #     volumeMounts:
      #       - name: rabbitmq-data
      #         mountPath: /var/lib/rabbitmq
      # volumes:
      #   - name: rabbitmq-data
      #     persistentVolumeClaim:
      #       claimName: rabbitmq-data-pvc
---
# rabbitmq-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq
spec:
  ports:
    - name: amqp # Add a name for the AMQP port
      port: 5672
      targetPort: 5672
    - name: management # Add a name for the management UI port
      port: 15672
      targetPort: 15672
  selector:
    app: rabbit-mq
